### ISSUE TITLE
Unexpected server response - Amazon

### ISSUE THREAD

**Issue by Znow** [senny/pdfjs_viewer-rails#4] opened 2015-05-22 08:41 UTC
Heya

Getting this error when trying to retrieve from Amazon:

```
PDF.js v1.0.907 (build: e9072ac)
Message: Unexpected server response (0) while retrieving PDF "https://xxxxx.s3.amazonaws.com/uploads/document/document/3/xxxxx.pdf".
```

**Comment by senny** [comment] 2016-06-02 08:29
Duplicate of #12. The linked issue also contains required steps to solve the issue.

**Closed by senny** 2016-06-02 08:29 UTC
